config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "articles#index"
  # get "/articles", to:"articles#index"
  # get "/articles/:id", to:"articles#show"
  resources :articles
  # resources :articles do
  #   collection do
  #     get :search
  #     post :search
  #   end
  # end
  get "/search", to:"articles#index"
  post "/search", to:"articles#search"

  get '/signup', to: "users#new"
  resources :users, except: [:new]

  get '/login', to: "sessions#new"
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


end

app/models/article.rb
require 'elasticsearch/model'

class Article < ApplicationRecord

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :body, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true

  settings index: { number_of_shards: 1 } do
    mapping dynamic: false do
      indexes :title,type: :text, analyzer: 'english'
      indexes :body, type: :text, analyzer: 'english'
      indexes :user_id, type: :integer
    end
  end


  def self.search(query)
    __elasticsearch__.search (
                               {
                                 query: {
                                   multi_match: {
                                     query: query,
                                     fields: ['title^5', 'body']
                                   }
                                 },
                                 highlight: {
                                   pre_tags: ['<mark>'],
                                   post_tags: ['</mark>'],
                                   fields: {
                                     title: {},
                                     body: {},
                                   }
                                 },
                                 suggest: {
                                   text: query,
                                   title: {
                                     term: {
                                       size: 1,
                                       field: :title
                                     }
                                   },
                                   body: {
                                     term: {
                                       size: 1,
                                       field: :body
                                     }
                                   }
                                 }
                               }
                             )
  end

end

app/controllers/articles_controller.rb
require 'json'

class ArticlesController < ApplicationController
  include ArticlesHelper
  @@admin_access_email = ["admin@gmail.com"]
  def index
    @articles = fetch_articles_redis
  end

  def show
    # get_article_from_redis(params[:id])
    @article = Article.find(params[:id])
  end

  def new
    if logged_in?
      @article = Article.new
    else
      render "sessions/new"
    end

  end

  def create
    @article = Article.new(article_params)
    if logged_in?
      @article.user = current_user
      if @article.save
        save_to_redis(@article)
        flash[:notice] = "Article was successfully created"
        redirect_to @article
      else
        render :new
      end
    else
      render "sessions/new"
    end

  end

  def edit
    @article = Article.find(params[:id])
    if logged_in? && (@article.user.eql?(current_user) || @@admin_access_email.include?(current_user.email.downcase) )
      @article = Article.find(params[:id])
    else
      flash[:danger] = "You cant update other's articles"
      redirect_to articles_path
    end
  end

  def update
    @article = Article.find(params[:id])
    if logged_in? && (@article.user.eql?(current_user) || @@admin_access_email.include?(current_user.email.downcase) )
      if(@article.update(article_params))
        save_to_redis(@article)
        redirect_to @article
      else
        flash[:danger] = "There was a problem while updating the Article Please retry"
        render :edit
      end
    else
      if logged_in?
        redirect_to @article
      else
        render "session/new"
      end
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if logged_in? && (@article.user.eql?(current_user) ||@@admin_access_email.include?(current_user.email.downcase))
      delete_from_redis(params[:id])
      @article.destroy
    end
    flash[:danger] = "You cant delete other's articles"
    redirect_to articles_path
  end

  def search
    query = params[:query]

    if query
      @articles = JSON.parse(Article.search(query).to_json)
    end
    @articles = @articles.map{|article| article["_source"]}
  end

  private
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def fetch_articles_redis
    keys = $redis.keys.select{|key| key.starts_with?("article") ? key : false}
    # p keys
    @articles = keys.map{|key| JSON.parse($redis.get(key))}
    # p @articles
    if @articles.length.eql?(0)
      @articles = Article.all
      @articles.each do|article|
        $redis.set("article"+article.id.to_s,article.to_json)
        $redis.expire("article"+article.id.to_s,5.hour.to_i)
      end
      return JSON.parse(@articles.to_json)
    end

    @articles
  end

  def save_to_redis(article)
    $redis.set("article"+article.id.to_s,article.to_json)
  end

  def get_article_from_redis(id)
    # print("article"+id.to_s)
    @article = $redis.get("article"+id.to_s)
    if @article.nil?
      @article = Article.find(id)
      save_to_redis(@article)
    end
    @article = JSON.parse($redis.get("article"+id.to_s))
  end

  def delete_from_redis(id)
    $redis.del("article"+id.to_s)
  end

end

app/views/articles/_form.html.erb
<%#= form_with model: article do |form| %>
<!--  <div>-->
<!--    <%#= form.label :title %><br>-->
    <%#= form.text_field :title %>
    <%# article.errors.full_messages_for(:title).each do |message| %>
<!--      <div><%#= message %></div>-->
    <%# end %>
<!--  </div>-->

<!--  <div>-->
<!--    <%#= form.label :body %><br>-->
<!--    <%#= form.text_area :body %><br>-->
    <%# article.errors.full_messages_for(:body).each do |message| %>
<!--      <div><%#= message %></div>-->
    <%# end %>
<!--  </div>-->

<!--  <div>-->
    <%#= form.submit %>
<!--  </div>-->
<%# end %>

<%#= link_to "home", root_path %>

<%# if @article.errors.any? %>
<!--  <h2>The following errors prevented the article from saving:</h2>-->
<!--  <ul>-->
    <%# @article.errors.full_messages.each do |msg|%>
<!--      <li><%#= msg %></li>-->
    <%# end %>
<!--  </ul>-->
<%# end %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-6">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :body %>
        </div>
        <div class="col-sm-6">
          <%= f.text_area :body, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-large' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<%= render 'shared/article', obj: @articles %>
<!--<div align="center">-->
  <%#= will_paginate %>
<!--</div>-->

<!--<h1>Articles</h1>-->

<!--<ul>-->
  <%# @articles.each do |article| %>
<!--    <li>-->
<!--      <a href="<%#= article_path(article) %>">-->
        <%#= article.title %>
<!--      </a>-->
<!--    </li>-->
  <%# end %>
<!--</ul>-->

<%#= link_to "New Article", new_article_path %>


<%#= link_to "home", root_path %>


<!--<h1 align="center">Listing all articles</h1>-->
<%# @articles.each do |article| %>
<!--  <div class="row">-->
<!--    <div class="col-xs-8 col-xs-offset-2">-->
<!--      <div class="well well-lg">-->
<!--        <div class="article-title">-->
          <%#= link_to article.title, article_path(article) %>
<!--        </div>-->
<!--        <div class="article-body">-->
          <%#= truncate(article.body, length: 100) %>
<!--        </div>-->
<!--        <div class="article-meta-details">-->
<!--          <small>Created by: <%#= article.user.username if article.user %>, <%#= time_ago_in_words(article.created_at) %> ago, last updated: <%#= time_ago_in_words(article.updated_at) %> ago</small>-->
<!--        </div>-->
<!--        <div class="article-actions">-->
          <%#= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%#= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<%# end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

<!--<h1>New Article</h1>-->

<%#= form_with model: @article do |form| %>
<!--  <div>-->
<!--    <%#= form.label :title %><br>-->
    <%#= form.text_field :title %>
    <%# @article.errors.full_messages_for(:title).each do |message| %>
<!--      <div><%#= message %></div>-->
    <%# end %>
<!--  </div>-->

<!--  <div>-->
<!--    <%#= form.label :body %><br>-->
    <%#= form.text_field :body %>
    <%# @article.errors.full_messages_for(:body).each do |message| %>
<!--      <div><%#= message %></div>-->
    <%# end %>
<!--  </div>-->

<!--  <div>-->
    <%#= form.submit %>
<!--  </div>-->
<%# end %>

app/views/articles/search.html.erb
<h1 align="center">Elastic search for articles</h1>
<%= render 'shared/article', obj: @articles %>

<%# @articles.each do |article| %>
<!--  <div class="row">-->
<!--    <div class="col-xs-8 col-xs-offset-2">-->
<!--      <div class="well well-lg">-->
<!--        <div class="article-title">-->
          <%#= link_to article.title, article_path(article) %>
<!--        </div>-->
<!--        <div class="article-body">-->
          <%#= truncate(article.body, length: 100) %>
<!--          <div class="article-meta-details">-->
<!--              <small>-->
<!--            <small>Created by: <%#= User.find_username(article["_source"]["user_id"]) %>,-->
<!--              <%#= time_ago_in_words(article.created_at) %> ago,-->
<!--              last updated: <%#= time_ago_in_words(article.updated_at) %> ago</small>-->
<!--          </div>-->
<!--        </div>-->
<!--        <div class="article-actions">-->
          <%#= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%#= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<%# end %>

app/views/articles/show.html.erb
<!--<h1><%#= @article.title %></h1>-->

<!--<p><%#= @article.body %></p>-->

<!--<small>Created by: <%#= @article.user.username if @article.user %>,-->
<!--  <%#= time_ago_in_words(@article.created_at) %> ago,-->
<!--  last updated: <%#= time_ago_in_words(@article.updated_at) %> ago</small>-->

<!--<ul>-->
<!--  <li><%#= link_to "Edit", edit_article_path(@article) %></li>-->
<!--  <li><%#= link_to "Destroy" , article_path(@article),method: :delete, data: { confirm: "Are you Sure?" } %></li>-->
<!--</ul>-->

<%#= link_to "home", root_path %>

<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
    <ul class="listing">
      <div class="row" align="center">
        <div class="col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
          <li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
          <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <h4 class="center body"><strong>body:</strong></h4>
  <hr>
  <%= simple_format(@article.body) %>
  <div class="article-actions">
    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
    <%= link_to "Back", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>