config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "articles#index"
  # get "/articles", to:"articles#index"
  # get "/articles/:id", to:"articles#show"
  resources :articles
  # resources :articles do
  #   collection do
  #     get :search
  #     post :search
  #   end
  # end
  get "/search", to:"articles#index"
  post "/search", to:"articles#search"

  get '/signup', to: "users#new"
  resources :users, except: [:new]

  get '/login', to: "sessions#new"
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Hey Blogger", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Create Article", new_article_path %></li>
<!--        <li class="dropdown">-->
<!--          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
<!--          <ul class="dropdown-menu">-->
<!--            <li><a href="#">Action</a></li>-->
<!--            <li><a href="#">Another action</a></li>-->
<!--            <li><a href="#">Something else here</a></li>-->
<!--            <li role="separator" class="divider"></li>-->
<!--            <li><a href="#">Separated link</a></li>-->
<!--            <li role="separator" class="divider"></li>-->
<!--            <li><a href="#">One more separated link</a></li>-->
<!--          </ul>-->
<!--        </li>-->
      </ul>
<!--      <form class="navbar-form navbar-left">-->

        <%#= form_for :search_articles, url: search_path, method: :post do |form| %>
          <%#= form.text_field :query, value: params[:search_articles].presence && params[:search_articles][:query] %>
          <%#= form.submit 'Search' %>
        <%# end %>
      <%= form_with(url: search_path, html: {class: "navbar-form navbar-left"}) do |form| %>
        <%= form.text_field :query %>
        <%= form.submit "Search" %>
      <% end %>

<!--        <div class="form-group">-->
<!--          <input type="text" class="form-control" placeholder="Search">-->
<!--        </div>-->
<!--        <button type="submit" class="btn btn-default">Submit</button>-->
<!--      </form>-->

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
          <li><%= link_to "Profile", user_path(:id => current_user), method: :get %></li>
        <% else %>
          <li><%= link_to "Log In", login_path, method: :get %></li>
          <li><%= link_to "Sign Up", signup_path, method: :get %></li>
<!--          <li class="dropdown">-->
<!--            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
<!--            <ul class="dropdown-menu">-->
<!--              <li><a href="#">Action</a></li>-->
<!--              <li><a href="#">Another action</a></li>-->
<!--              <li><a href="#">Something else here</a></li>-->
<!--              <li role="separator" class="divider"></li>-->
<!--              <li><a href="#">Separated link</a></li>-->
<!--            </ul>-->
<!--          </li>-->
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= debug(params) if Rails.env.development? %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <% flash.each do |name, msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
    <% end %>
    <%= yield %>
  </body>
</html>